import { acquireContext, releaseContext } from "./browser";
import type { BrowserContext } from "playwright-core";

export interface ScreenshotOptions {
  /** URL to capture. Mutually exclusive with `html`. */
  url?: string;
  /** Raw HTML to render and capture. Mutually exclusive with `url`. */
  html?: string;
  /** Output format */
  format?: "png" | "jpeg" | "pdf";
  /** Viewport width in pixels (default: 1280) */
  width?: number;
  /** Viewport height in pixels (default: 720) */
  height?: number;
  /** Capture full scrollable page (default: false) */
  fullPage?: boolean;
  /** JPEG quality 0-100 (only for jpeg format, default: 80) */
  quality?: number;
  /** Device scale factor (default: 1) */
  deviceScaleFactor?: number;
  /** Wait for this many ms after page load (default: 0) */
  waitAfterLoad?: number;
  /** CSS selector to wait for before capturing */
  waitForSelector?: string;
  /** Dark mode (default: false) */
  darkMode?: boolean;
  /** Add watermark branding (default: true for free tier) */
  watermark?: boolean;
}

export interface ScreenshotResult {
  data: Buffer;
  contentType: string;
}

const NAVIGATION_TIMEOUT = parseInt(
  process.env.NAVIGATION_TIMEOUT_MS || "30000",
  10
);

/**
 * Take a screenshot with the given options.
 * Manages browser context lifecycle automatically.
 */
export async function takeScreenshot(
  options: ScreenshotOptions
): Promise<ScreenshotResult> {
  const {
    url,
    html,
    format = "png",
    width = 1280,
    height = 720,
    fullPage = false,
    quality = 80,
    deviceScaleFactor = 1,
    waitAfterLoad = 0,
    waitForSelector,
    darkMode = false,
    watermark = true,
  } = options;

  if (!url && !html) {
    throw new Error("Either 'url' or 'html' must be provided.");
  }
  if (url && html) {
    throw new Error("Provide either 'url' or 'html', not both.");
  }

  let context: BrowserContext | null = null;

  try {
    context = await acquireContext();

    const page = await context.newPage();
    await page.setViewportSize({ width, height });

    if (darkMode) {
      await page.emulateMedia({ colorScheme: "dark" });
    }

    if (deviceScaleFactor !== 1) {
      await page.setViewportSize({ width, height });
    }

    // Navigate
    if (url) {
      await page.goto(url, {
        waitUntil: "networkidle",
        timeout: NAVIGATION_TIMEOUT,
      });
    } else if (html) {
      await page.setContent(html, {
        waitUntil: "networkidle",
        timeout: NAVIGATION_TIMEOUT,
      });
    }

    // Optional waits
    if (waitForSelector) {
      await page.waitForSelector(waitForSelector, {
        timeout: NAVIGATION_TIMEOUT,
      });
    }
    if (waitAfterLoad > 0) {
      await page.waitForTimeout(Math.min(waitAfterLoad, 10000));
    }

    // Add watermark for free tier (brand exposure)
    if (watermark && format !== "pdf") {
      await page.evaluate(() => {
        const badge = document.createElement("div");
        badge.innerText = "Generated by LandingWork.dev";
        badge.style.cssText = `
          position: fixed;
          bottom: 8px;
          right: 12px;
          font-family: -apple-system, BlinkMacSystemFont, sans-serif;
          font-size: 11px;
          color: rgba(255,255,255,0.7);
          background: rgba(0,0,0,0.55);
          padding: 3px 8px;
          border-radius: 4px;
          z-index: 2147483647;
          pointer-events: none;
        `;
        document.body.appendChild(badge);
      });
    }

    // Capture
    if (format === "pdf") {
      const data = await page.pdf({
        width: `${width}px`,
        printBackground: true,
      });
      return { data: Buffer.from(data), contentType: "application/pdf" };
    }

    const screenshotOptions: {
      type: "png" | "jpeg";
      fullPage: boolean;
      quality?: number;
    } = {
      type: format,
      fullPage,
    };

    if (format === "jpeg") {
      screenshotOptions.quality = Math.min(100, Math.max(0, quality));
    }

    const data = await page.screenshot(screenshotOptions);
    const contentType = format === "png" ? "image/png" : "image/jpeg";

    return { data: Buffer.from(data), contentType };
  } finally {
    if (context) {
      await releaseContext(context);
    }
  }
}
