import type { FastifyRequest, FastifyReply } from "fastify";
import { extractApiKey, validateApiKey } from "../lib/auth.js";
import { checkRateLimit } from "../lib/rateLimit.js";
import { acquireContext, releaseContext } from "../lib/browser.js";
import type { BrowserContext } from "playwright-core";

interface ScreenshotBody {
  url?: string;
  html?: string;
  format?: "png" | "jpeg" | "pdf";
  width?: number;
  height?: number;
  fullPage?: boolean;
  quality?: number;
  darkMode?: boolean;
  waitAfterLoad?: number;
  waitForSelector?: string;
}

export async function screenshotRoute(request: FastifyRequest<{ Body: ScreenshotBody }>, reply: FastifyReply) {
  // Auth
  const key = extractApiKey(request.headers.authorization) || (request.headers["x-api-key"] as string);
  if (!validateApiKey(key)) {
    return reply.status(401).send({ error: "Unauthorized", message: "Invalid or missing API key." });
  }

  // Rate limit
  const rl = checkRateLimit(key!);
  if (!rl.allowed) {
    return reply.status(429).send({ error: "Rate limit exceeded", remaining: 0 });
  }

  const { url, html, format = "png", width = 1280, height = 720, fullPage = false, quality = 80, darkMode = false, waitAfterLoad = 0, waitForSelector } = request.body || {};

  if (!url && !html) return reply.status(400).send({ error: "Provide 'url' or 'html'." });
  if (url && html) return reply.status(400).send({ error: "Provide 'url' or 'html', not both." });

  let context: BrowserContext | null = null;
  try {
    context = await acquireContext();
    const page = await context.newPage();
    await page.setViewportSize({ width, height });
    if (darkMode) await page.emulateMedia({ colorScheme: "dark" });

    const TIMEOUT = parseInt(process.env.NAVIGATION_TIMEOUT_MS || "30000", 10);
    if (url) await page.goto(url, { waitUntil: "networkidle", timeout: TIMEOUT });
    else await page.setContent(html!, { waitUntil: "networkidle", timeout: TIMEOUT });

    if (waitForSelector) await page.waitForSelector(waitForSelector, { timeout: TIMEOUT });
    if (waitAfterLoad > 0) await page.waitForTimeout(Math.min(waitAfterLoad, 10000));

    // Watermark
    await page.evaluate(() => {
      const badge = document.createElement("div");
      badge.innerText = "Generated by SnapForge.dev";
      badge.style.cssText = "position:fixed;bottom:8px;right:12px;font-family:sans-serif;font-size:11px;color:rgba(255,255,255,0.7);background:rgba(0,0,0,0.55);padding:3px 8px;border-radius:4px;z-index:2147483647;";
      document.body.appendChild(badge);
    });

    if (format === "pdf") {
      const data = await page.pdf({ width: `${width}px`, printBackground: true });
      return reply.header("content-type", "application/pdf").header("x-ratelimit-remaining", rl.remaining).send(Buffer.from(data));
    }

    const opts: any = { type: format, fullPage };
    if (format === "jpeg") opts.quality = Math.min(100, Math.max(0, quality));
    const data = await page.screenshot(opts);
    const ct = format === "png" ? "image/png" : "image/jpeg";
    return reply.header("content-type", ct).header("x-ratelimit-remaining", rl.remaining).send(Buffer.from(data));
  } catch (e: any) {
    if (e.message?.includes("at capacity")) return reply.status(503).send({ error: e.message });
    return reply.status(500).send({ error: "Screenshot failed", message: e.message });
  } finally {
    if (context) await releaseContext(context);
  }
}
